-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Apr 02, 2025 at 01:26 PM
-- Server version: 8.0.31
-- PHP Version: 8.0.26

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `supercar`
--

-- --------------------------------------------------------

--
-- Table structure for table `voiture`
--

DROP TABLE IF EXISTS `voiture`;
CREATE TABLE IF NOT EXISTS `voiture` (
  `id` int NOT NULL AUTO_INCREMENT,
  `car_num` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `make` varchar(30) NOT NULL,
  `model` varchar(50) NOT NULL,
  `type` varchar(50) NOT NULL,
  `price` varchar(10) NOT NULL,
  `image` varchar(255) NOT NULL,
  `explore_img1` varchar(255) NOT NULL,
  `explore_img2` varchar(255) NOT NULL,
  `explore_img3` varchar(255) NOT NULL,
  `overview_fr` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `overview_en` text NOT NULL,
  `eng_type_fr` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `eng_type_en` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  `key_fr` text NOT NULL,
  `key_en` text NOT NULL,
  `puissance` int NOT NULL,
  `transmission_fr` varchar(60) NOT NULL,
  `transmission_en` varchar(60) NOT NULL,
  `boite_vitesse` tinyint NOT NULL,
  `max_speed` int NOT NULL,
  `accel` decimal(15,1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

--
-- Dumping data for table `voiture`
--

INSERT INTO `voiture` (`id`, `car_num`, `make`, `model`, `type`, `price`, `image`, `explore_img1`, `explore_img2`, `explore_img3`, `overview_fr`, `overview_en`, `eng_type_fr`, `eng_type_en`, `key_fr`, `key_en`, `puissance`, `transmission_fr`, `transmission_en`, `boite_vitesse`, `max_speed`, `accel`) VALUES
(1, 'car1', 'Aston Martin', 'DB12 Volante', 'Cabriolet', '€275,000', 'Voiture_Images/db12_cabriolet.webp', 'images/DB12-front.JPG', 'images/DB12-side.jpeg', 'images/DB12-30.jpeg', 'L\'Aston Martin DB12 est la dernière grande routière de luxe (GT) d\'Aston Martin, dévoilée en 2023 pour succéder à la DB11. Surnommée la première « Super Tourer » au monde, la DB12 représente un grand pas en avant, offrant plus de puissance, une meilleure tenue de route, une technologie de pointe et un intérieur entièrement redessiné.', 'The Aston Martin DB12 is the latest luxury grand tourer (GT) from Aston Martin, unveiled in 2023 as the successor to the DB11. Dubbed the world\'s first \"Super Tourer,\" the DB12 represents a major step forward, offering more power, sharper handling, cutting-edge technology, and a completely redesigned interior.', 'V8 4.0L Biturbo', '4.0L Twin-Turbocharged V8', '• Cockpit entièrement repensé avec cuir haut de gamme, Alcantara et fibre de carbone\r\n• Phare LED plus fin avec technologie d\'éclairage avancée\r\n• Système audio Bang & Olufsen haut de gamme pour une expérience sonore immersive\r\n• Apple CarPlay et Android Auto avec le nouveau logiciel maison Aston Martin\r\n• Packages intérieurs et extérieurs en fibre de carbone optionnels', '', 680, 'Automatique À 8 Rapports Avec Différentiel Arrière Électroni', '8-speed automatic with electronic rear differential', 8, 325, '3.6'),
(2, 'car2', 'Aston Martin', 'DBX', 'SUV', '€250,000', 'Voiture_Images/dbx2.webp', 'images/DBX-front.png', 'images/DBX-side.jpeg', 'images/DBX-30.jpeg', 'L\'Aston Martin DBX est le premier SUV de luxe de la marque, conçu pour allier les performances d\'une voiture de sport à la praticité d\'un SUV. Introduit en 2020, le DBX représente l\'expansion d\'Aston Martin au-delà de ses traditionnels grands tours et supercars, offrant un luxe haut de gamme, des capacités tout-terrain et des performances exaltantes en un seul ensemble.', 'The Aston Martin DBX is the brand’s first luxury SUV, designed to blend the performance of a sports car with the practicality of an SUV. Introduced in 2020, the DBX represents Aston Martin’s expansion beyond its traditional grand tourers and supercars, offering high-end luxury, off-road capability, and exhilarating performance in one package.', 'V8 4.0L Biturbo', '4.0L Twin-Turbocharged V8', '• Cabine spacieuse avec cinq sièges et un grand espace de chargement\n• Suspension pneumatique ajustable avec contrôle actif du roulis pour une maniabilité dynamique\n• Apple CarPlay, système audio haut de gamme et fonctionnalités avancées d\'assistance à la conduite\n• Les acheteurs peuvent choisir parmi des finitions intérieures et extérieures sur mesure, y compris le programme de personnalisation Q par Aston Martin\n• Grille avant plus large pour un meilleur refroidissement', '', 542, 'Automatique À 9 Rapports', '9-speed automatic', 9, 291, '4.5'),
(3, 'car3', 'Aston Martin', 'Valour', 'Coupe', '€275,000', 'Voiture_Images/valour.webp', 'images/valour-front.png', 'images/valour-side.png', 'images/valour-30.png', 'L\'Aston Martin Valour est une voiture de grand tourisme V12 en édition limitée ultra-exclusive qui rend hommage au riche héritage de la marque tout en intégrant des technologies de pointe en matière de performances. Inspirée par la légendaire Aston Martin V8 Vantage des années 1970 et 1980, la Valour est une supercar à boîte manuelle qui allie une dynamique de conduite brute au luxe moderne.', 'The Aston Martin Valour is an ultra-exclusive, limited-edition V12 grand tourer that pays homage to the brand’s rich heritage while incorporating cutting-edge performance technology. Inspired by the legendary Aston Martin V8 Vantage from the 1970s and 1980s, the Valour is a manual-only supercar, blending raw driving dynamics with modern luxury.', 'V12 Biturbo De 5.2L', '5.2L Twin-Turbocharged V12', '• Cabine artisanale avec Alcantara, cuir et garnitures en fibre de carbone\n• Réglage du châssis le plus avancé d\'Aston Martin pour une conduite engageante\n• Diffuseur avant agressif, bas de caisse profonds et un aileron arrière distinctif\n• Propulsion arrière pour un engagement mécanique pur\n• Seulement 110 unités produites dans le monde, ce qui en fait un objet de collection exclusif\n', '', 705, 'Boîte Manuelle À 6 Rapports', '6-speed manual gearbox', 6, 320, '3.5'),
(4, 'car4', 'Aston Martin', 'Vanquish', 'Coupe', '€200,000', 'Voiture_Images/vanquish1.webp', 'images/Vanquish-Front.png', 'images/Vanquish-Side.jpeg', 'images/Vanquish-30.jpeg', 'L\'Aston Martin Vanquish est une voiture de grand tourisme (GT) très performante qui incarne le luxe, la puissance et l\'ingénierie de pointe. Présentée pour la première fois en 2001, elle a fait l\'objet de nombreux perfectionnements, les derniers modèles alliant un style agressif, un moteur puissant et une technologie moderne. Conçue pour succéder à la DBS, la Vanquish est connue pour son intérieur artisanal, sa carrosserie légère en fibre de carbone et son moteur V12 atmosphérique qui offre une expérience de conduite exaltante.', 'The Aston Martin Vanquish is a high-performance grand tourer (GT) that epitomizes luxury, power, and cutting-edge engineering. Originally introduced in 2001, it has undergone multiple refinements, with the latest models blending aggressive styling, a powerful engine, and modern technology. Designed as the successor to the DBS, the Vanquish is known for its handcrafted interior, lightweight carbon-fiber body, and a naturally aspirated V12 engine that delivers an exhilarating driving experience.', 'V12 Atmosphérique De 5.9L', '5.9L Naturally Aspirated V12', '• Intérieur en cuir haut de gamme\n• Système de caméra à 360 degrés\n• Apple CarPlay sans fil & Android Auto\n• Configuration d\'échappement à quatre sorties pour un son agressif\n', '<li>Premium Leather Interior</li><br />\r\n                <li>360-degree Camera System</li><br />\r\n                <li>Wireless Apple CarPlay & Android Auto</li><br />\r\n                <li>Quad-exhaust setup for an aggressive sound</li>', 565, 'Transmission Automatique Touchtronic III À 8 Rapports', '8-speed Touchtronic III automatic transmission', 7, 320, '3.5'),
(5, 'car5', 'Aston Martin', 'Vantage', 'Coupe', '€175,000', 'Voiture_Images/vantage_coupe.webp', 'images/Vantage-front.png', 'images/Vantage-side.jpeg', 'images/Vantage-30.jpeg', 'L\'Aston Martin Vantage est une voiture de sport de luxe très performante qui allie le savoir-faire britannique à un style agressif et à des capacités de conduite dynamiques. Présentée pour la première fois en 1977, la Vantage a évolué au fil des générations, les versions modernes offrant un châssis léger, des moteurs puissants et une aérodynamique avancée. Conçue pour rivaliser avec la Porsche 911, la Mercedes-AMG GT et la McLaren Artura, la Vantage se distingue par son design audacieux, son intérieur artisanal et ses performances palpitantes.', 'The Aston Martin Vantage is a high-performance luxury sports car that blends British craftsmanship with aggressive styling and dynamic driving capabilities. First introduced in 1977, the Vantage has evolved through multiple generations, with the modern versions offering a lightweight chassis, powerful engine options, and advanced aerodynamics. Designed to compete with the Porsche 911, Mercedes-AMG GT, and McLaren Artura, the Vantage stands out with its bold design, handcrafted interior, and thrilling performance.', 'V8 Biturbo De 4.0L', '4.0L Twin-Turbocharged V8', '• Fabriqué à la main avec du cuir, de l\'Alcantara et des garnitures en fibre de carbone • Splitter avant aérodynamique, grille agressive, diffuseur arrière sculpté et éclairage LED élégant • Modes Sport, Sport+ et Track sélectionnables pour une expérience de conduite personnalisable • Écran tactile de 8 pouces, Apple CarPlay, navigation et audio premium Aston Martin • Freins en céramique carbone disponibles pour une puissance de freinage améliorée', '', 503, 'Manuelle À 7 Rapports', '7-speed manual', 7, 314, '3.6'),
(6, 'car6', 'Maserati', 'Ghibli', 'Sedan', '€225,000', 'Voiture_Images/ghibli1.webp', 'images/ghibli-front.avif', 'images/ghibli-side.jpeg', 'images/ghibli-30.png', 'La Maserati Ghibli est une berline sportive de luxe qui allie l\'élégance italienne, des performances palpitantes et un savoir-faire haut de gamme. Positionnée en dessous de la Quattroporte, la Ghibli offre une alternative plus dynamique et plus agile tout en conservant le design et l\'expérience de conduite propres à Maserati.', 'The Maserati Ghibli is a luxury sports sedan that blends Italian elegance, thrilling performance, and premium craftsmanship. Positioned below the Quattroporte, the Ghibli offers a more dynamic and agile alternative while maintaining Maserati’s signature design and driving experience.', 'V8 3.8L Biturbo', '3.8L Twin-Turbo V8', '• Cuir italien haut de gamme, bois ou garniture en fibre de carbone • Système d\'échappement à quatre sorties • Système d\'infodivertissement Maserati Intelligent Assistant de 12,3 pouces  • Caméra à vue panoramique à 360 degrés • Freinage d\'urgence automatique', '', 580, 'Automatique ZF À 8 Rapports', '8-speed ZF automatic', 8, 326, '5.7'),
(7, 'car7', 'Maserati', 'GT2 Stradale', 'Coupe', '€400,000', 'Voiture_Images/gt2_stra1.webp', 'images/stradale-front.jpg', 'images/stradale-side.jpg', 'images/stradale-30.jpg', 'La Maserati GT2 Stradale est une version routière ultraperformante de la voiture de course Maserati GT2, conçue pour offrir une puissance, une aérodynamique et une maniabilité inspirées du circuit, tout en restant utilisable sur les routes publiques. Elle représente le retour de Maserati dans les courses de GT, s\'inspirant de la MC12 et intégrant les dernières innovations en matière d\'ingénierie légère et d\'aérodynamique avancée.', 'The Maserati GT2 Stradale is an ultra-high-performance road-legal version of the Maserati GT2 race car, designed to deliver track-inspired power, aerodynamics, and handling while remaining usable on public roads. It represents Maserati’s return to GT racing, drawing inspiration from the MC12 and integrating the latest in lightweight engineering and advanced aerodynamics.', 'V6 Nettuno 3.0L Biturbo', '3.0L Twin-Turbocharged V6 Nettuno', '• Éléments aérodynamiques avant et arrière extrêmes pour un appui optimal • Sièges baquets de course avec option harnais 6 points • Aérodynamique active avec réglages ajustables pour la route et la piste • Différentiel électronique avancé pour une maniabilité de précision • Options de personnalisation sur mesure grâce au programme Fuoriserie de Maserati', '', 630, 'Boîte Séquentielle À 6 Rapports Ou Version Adaptée À La Rout', '6-speed sequential gearbox or road-tuned version with paddle', 6, 300, '3.0'),
(8, 'car8', 'Maserati', 'Levante', 'SUV', '€190,000', 'Voiture_Images/Levante1.webp', 'images/levante-front.JPG', 'images/levante-side.JPG', 'images/levante-30.JPG', 'Le Maserati Levante est un SUV de luxe qui incarne la signature artisanale italienne de la marque, l\'ingénierie haute performance et le design élégant. Lancé en 2016, le Levante est le tout premier SUV de Maserati, alliant la dynamique d\'une voiture de sport au confort et à la praticité d\'un SUV. Nommé d\'après un vent méditerranéen connu pour son intensité soudaine, le Levante est conçu pour offrir des performances palpitantes, des intérieurs luxueux et une technologie de pointe.', 'The Maserati Levante is a luxury SUV that embodies the brand\'s signature Italian craftsmanship, high-performance engineering, and elegant design. Introduced in 2016, the Levante is Maserati’s first-ever SUV, blending sports car dynamics with the comfort and practicality of an SUV. Named after a Mediterranean wind known for its sudden intensity, the Levante is designed to deliver thrilling performance, luxurious interiors, and cutting-edge technology.', 'V8 Biturbo De 3,8 Litres', '3.8L twin-turbo V8', '<li>Garnitures en cuir, bois et fibre de carbone de haute qualité</li><br />\r\n                <li>Toit ouvrant panoramique</li><br />\r\n                <li>Systèmes audio haut de gamme (Harman Kardon ou Bowers & Wilkins disponibles)</li><br />\r\n                <li>Système d\'assistance à la conduite avancé</li><br />\r\n                <li>Alerte de franchissement de ligne</li><br />\r\n                <li>Surveillance des angles morts</li>', '', 572, 'Automatique À 8 Rapports', '8-speed automatic', 8, 302, '6.0'),
(9, 'car9', 'Maserati', 'MC20 Cielo', 'Cabriolet', '€210,000', 'Voiture_Images/MC202.webp', 'images/cielo-front.JPG', 'images/cielo-side.JPG', 'images/cielo-30.JPG', 'La Maserati MC20 Cielo est la variante à toit ouvert de la supercar MC20, qui allie des performances époustouflantes à l\'émotion de la conduite en plein air. « Cielo », qui signifie “ciel” en italien, met l\'accent sur son toit en verre électrochrome rétractable, qui passe de la transparence à l\'opacité en un instant, améliorant ainsi l\'expérience de conduite.', 'The Maserati MC20 Cielo is the open-top variant of the MC20 supercar, combining breathtaking performance with the thrill of open-air driving. \"Cielo,\" meaning \"sky\" in Italian, emphasizes its retractable electrochromic glass roof, which transitions from transparent to opaque in an instant, enhancing the driving experience.', 'V6 Nettuno 3.0L Biturbo', '3.0L Twin-Turbo Nettuno V6', '<li>Matériaux en fibre de carbone, Alcantara et cuir</li><br />\r\n                <li>Toit en verre électrochromatique</li><br />\r\n                <li>Porte papillon pour un style dramatique et un accès facile à l\'habitacle</li><br />\r\n                <li>Modes de conduite : GT, Sport, Corsa et Wet</li><br />\r\n                <li>Différentiel à glissement limité pour une meilleure adhérence</li><br />\r\n                <li>Production limitée pour plus d\'exclusivité</li>', '', 630, 'Automatique À Double Embrayage 8 Vitesses', '8-speed dual-clutch automatic', 8, 320, '3.0'),
(10, 'car10', 'Maserati', 'Quattroporte', 'Sedan', '€175,000', 'Voiture_Images/quattro11.webp', 'images/quattraporte-front.jpg', 'images/quattraporte-side.jpg', 'images/quattraporte-30.jpg', 'La Maserati Quattroporte est une berline sportive de luxe de grande taille qui allie l\'élégance italienne, le luxe artisanal et des performances exaltantes. En tant que berline phare de Maserati, la Quattroporte a un long héritage qui remonte à 1963, ce qui en fait l\'un des noms les plus distingués de l\'histoire de l\'automobile de luxe.', 'The Maserati Quattroporte is a full-size luxury sports sedan that combines Italian elegance, handcrafted luxury, and exhilarating performance. As Maserati’s flagship sedan, the Quattroporte has a long legacy dating back to 1963, making it one of the most distinguished names in luxury automotive history.', 'V6 Biturbo De 3.0L', '3.0L Twin-Turbo V6', '<li>Silhouette aérodynamique élégante avec des proportions de coupé</li><br />\r\n                <li>Climatisation automatique à quatre zones pour un confort ultime</li><br />\r\n                <li>Différentiel à glissement limité pour une traction améliorée</li><br />\r\n                <li>Alerte de sortie de voie & assistance au maintien de voie</li><br />\r\n                <li>Régulateur de vitesse adaptatif</li>', '<li>Sleek, aerodynamic silhouette with coupe-like proportions</li><br />\r\n                <li>Four-zone automatic climate control for ultimate comfort</li><br />\r\n                <li>Limited-slip differential for improved traction</li><br />\r\n                <li>Lane departure warning & lane-keeping assist</li><br />\r\n                <li>Adaptive cruise control</li><br />', 430, 'Automatique ZF À 8 Rapports', '8-speed ZF automatic', 8, 288, '5.5'),
(11, 'car11', 'Porsche', 'Cayenne GTS', 'SUV', '€200,000', 'Voiture_Images/cayenne_gts1.png', 'images/cayenne-front.avif', 'images/cayenne-side.avif', 'images/cayenne-court.jpg', 'Le Porsche Cayenne GTS est un SUV de luxe hautes performances qui allie l\'agilité d\'une voiture de sport à la praticité d\'un SUV. Situé entre le Cayenne S et le Cayenne Turbo, le modèle GTS met l\'accent sur une dynamique de conduite améliorée, un design plus sportif et une note d\'échappement plus agressive.', 'The Porsche Cayenne GTS is a high-performance luxury SUV that blends sportscar agility with SUV practicality. Positioned between the Cayenne S and the Cayenne Turbo, the GTS model focuses on enhanced driving dynamics, a sportier design, and a more aggressive exhaust note.', 'V8 4.0L À Double Turbocompresseur', '4.0L Twin-Turbocharged V8', '<li>Revêtement exclusif Alcantara® GTS et garniture en cuir</li><br />\r\n                <li>Options de garniture intérieure en fibre de carbone ou aluminium brossé</li><br />\r\n                <li>Phare et feux arrière LED teintés sombres</li><br />\r\n                <li>Contrôle dynamique du châssis Porsche pour une meilleure stabilité en virage</li><br />\r\n                <li>Régulateur de vitesse adaptatif</li><br />\r\n                <li>Option de pack sportif léger pour une réduction de poids</li>', '<li>GTS-exclusive Alcantara® upholstery and leather trim</li><br />\r\n                <li>Carbon-fiber or brushed aluminum interior trim options</li><br />\r\n                <li>Dark-tinted LED headlights and taillights</li><br />\r\n                <li>Porsche Dynamic Chassis Control for improved cornering stability</li><br />\r\n                <li>Adaptive Cruise Control</li><br />\r\n                <li>Optional Lightweight Sports Package for weight reduction</li>', 500, 'Automatique Tiptronic S', '8-speed Tiptronic S automatic', 8, 275, '4.5'),
(12, 'car12', 'Porsche', '911 Turbo S', 'Coupe', '€325,000', 'Voiture_Images/911turbo_s1.png', 'images/911turbos-front', 'images/911turbos-side', 'images/911turbos-30', 'La Porsche 911 Turbo S est le summum de la performance, du luxe et de l\'ingénierie de pointe dans la gamme 911. En tant que 911 la plus rapide et la plus puissante, la Turbo S offre une accélération digne d\'une supercar, une maniabilité exceptionnelle et une facilité d\'utilisation au quotidien, ce qui en fait l\'une des voitures hautes performances les plus complètes au monde.', 'The Porsche 911 Turbo S is the pinnacle of performance, luxury, and cutting-edge engineering in the 911 lineup. As the fastest and most powerful 911, the Turbo S delivers supercar-level acceleration, exceptional handling, and everyday usability, making it one of the most well-rounded high-performance cars in the world.', '6 Cylindres À Plat De 3,8 Litres À Double Turbocompresseur', '3.8L Twin-Turbocharged Flat-6', '<li>Roues exclusives à verrouillage central forgées 911 Turbo S</li><br />\r\n                <li>Carrosserie élargie avec prises d\'air spécifiques Turbo pour un meilleur refroidissement</li><br />\r\n                <li>Roues exclusives à verrouillage central forgées 911 Turbo S</li><br />\r\n                <li>Système audio surround BOSE® premium</li><br />\r\n                <li>Stabilisation active contre le roulis pour une meilleure stabilité en virage</li><br />\r\n                <li>Freinage d\'urgence automatique avec détection des piétons</li><br />\r\n                <li>Assistance à la vision nocturne</li>', '<li>Exclusive 911 Turbo S forged center-lock wheels</li><br />\r\n                <li>Wider body with Turbo-specific air intakes for improved cooling</li><br />\r\n                <li>Exclusive 911 Turbo S forged center-lock wheels</li><br />\r\n                <li>BOSE® premium surround sound system</li><br />\r\n                <li>Active anti-roll stabilization for better cornering stability</li><br />\r\n                <li>Automatic Emergency Braking with pedestrian detection</li><br />\r\n                <li>Night Vision Assist</li>', 650, 'Automatique Porsche Doppelkupplung', '8-speed Porsche Doppelkupplung automatic', 8, 330, '2.7'),
(13, 'car13', 'Porsche', '911 GT3 RS', 'Coupe', '€600,000', 'Voiture_Images/911gt3rs1.png', 'images/911gt3rs-front', 'images/911gt3rs-side.webp', 'images/911gt3rs-30.webp', 'La Porsche 911 GT3 RS est l\'expression ultime de l\'ingénierie axée sur la piste dans la gamme 911. Conçue pour offrir un maximum d\'aérodynamisme, de légèreté et de maniabilité, la GT3 RS est une machine de précision à moteur atmosphérique et à propulsion arrière, conçue pour dominer la piste et la route.', 'The Porsche 911 GT3 RS is the ultimate expression of track-focused engineering in the 911 lineup. Designed for maximum aerodynamics, lightweight performance, and razor-sharp handling, the GT3 RS is a naturally aspirated, rear-wheel-drive precision machine, built to dominate both the track and the road.', '6 cylindres à plat de 4,0 Litres', '4.0L Naturally Aspirated Flat-6', '', '', 525, 'Porsche Doppelkupplung (PDK) automatique', 'Porsche Doppelkupplung (PDK) automatic', 7, 296, '3.2'),
(14, 'car14', 'Porsche', 'Taycan', 'Sedan', '€400,000', 'Voiture_Images/taycan1.png', 'images/taycan-front', 'images/taycan-side.webp', 'images/taycan-30.webp', 'La Porsche Taycan est la première berline sportive entièrement électrique de Porsche, combinant une technologie EV de pointe avec les performances, la maniabilité et le luxe légendaires de Porsche. Depuis son lancement en 2019, la Taycan a redéfini la conduite électrique en offrant une accélération palpitante, un aérodynamisme avancé et un intérieur haut de gamme, ce qui en fait une concurrente sérieuse de la Tesla Model S Plaid, de l\'Audi e-tron GT et de la Mercedes-AMG EQS.', 'The Porsche Taycan is Porsche’s first fully electric sports sedan, combining cutting-edge EV technology with Porsche’s legendary performance, handling, and luxury. Since its launch in 2019, the Taycan has redefined electric driving by offering thrilling acceleration, advanced aerodynamics, and a premium interior, making it a serious competitor to the Tesla Model S Plaid, Audi e-tron GT, and Mercedes-AMG EQS.', 'Batterie : Performance Battery Plus (93,4 KWh) Disponible Pour Une Autonomie Étendue', 'Performance Battery Plus (93.4 kWh)', '<li>Cuir premium, Race-Tex (suède synthétique écologique) ou garnitures intérieures en fibre de carbone</li><br />\r\n                <li>Bandeau lumineux LED sur toute la largeur avec le script Porsche</li><br />\r\n                <li>Apple CarPlay sans fil & Android Auto</li><br />\r\n                <li>Gestion active de la suspension Porsche (PASM) pour une qualité de conduite adaptable</li><br />\r\n                <li>Assistance au maintien de voie & aide au changement de voie</li><br />\r\n                <li>Caméra à 360 degrés pour une vue complète</li><br />\r\n                <li>Régulateur de vitesse adaptatif</li>', '<li>Sleek, aerodynamic silhouette with coupe-like proportions</li><br />\r\n                <li>Four-zone automatic climate control for ultimate comfort</li><br />\r\n                <li>Limited-slip differential for improved traction</li><br />\r\n                <li>Lane departure warning & lane-keeping assist</li><br />\r\n                <li>Adaptive cruise control</li><br />', 408, 'Boîte De Vitesses À Deux Rapports Sur L\'Essieu Arrière Pour ', 'Two-speed transmission on the rear axle for optimized effici', 2, 230, '5.4'),
(15, 'car15', 'Porsche', 'Panamera', 'Sedan', '€350,000', 'Voiture_Images/panamera1.png', 'images/panamera-front.webp', 'images/panamera-side.webp', 'images/panamera-30.webp', 'La Porsche Panamera est une berline sportive de luxe qui associe une conduite dynamique et performante à un confort haut de gamme et à une technologie de pointe. Lancée en 2009, la Panamera a été conçue pour apporter la maniabilité et la puissance caractéristiques de Porsche à une plateforme grand tourisme à quatre portes, offrant ainsi l\'agilité d\'une voiture de sport et la praticité d\'une berline exécutive.', 'The Porsche Panamera is a luxury sports sedan that combines high-performance driving dynamics with premium comfort and cutting-edge technology. Originally introduced in 2009, the Panamera was designed to bring Porsche’s signature handling and power to a four-door grand touring platform, offering sports car agility with executive sedan practicality.', 'V6 2.9L Biturbo', '2.9L Twin-Turbo V6', '<li>Options de garniture en cuir, fibre de carbone ou bois de haute qualité</li><br />\r\n                <li>Climatisation automatique à quatre zones</li><br />\r\n                <li>Apple CarPlay sans fil & Android Auto</li><br />\r\n                <li>Modes de conduite : Normal, Sport, Sport Plus, Individuel</li><br />\r\n                <li>Freinage d\'urgence automatique</li><br />\r\n                <li>Caméra à 360 degrés pour une vue complète</li><br />\r\n                <li>Régulateur de vitesse adaptatif</li>', '<li>High-quality leather, carbon fiber, or wood trim options</li><br />\r\n                <li>Four-zone automatic climate control</li><br />\r\n                <li>Wireless Apple CarPlay & Android Auto</li><br />\r\n                <li>Drive modes: Normal, Sport, Sport Plus, Individual</li><br />\r\n                <li>Automatic Emergency Braking</li><br />\r\n                <li>360-degree Surround View Camera</li><br />\r\n                <li>Adaptive Cruise Control</li>', 353, 'Automatique PDK À 8 Vitesses', '8-speed PDK automatic', 8, 272, '5.1');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
